# ***Assignment 4 Cognitive Computing*** 
***Shivam Kumar***
***102497026***

***Question1***
Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])
print("Original Array = ",arr)
arr_add = arr+2
print("After Addition",arr_add)
arr_mul = arr*3
print("After Multiply",arr_mul)
arr_div = arr/2
print("After Divde",arr_div)

Original Array =  [1 2 3 4 5]
After Addition [3 4 5 6 7]
After Multiply [ 3  6  9 12 15]
After Divde [0.5 1.  1.5 2.  2.5]


***Question2*** 
Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [5]:
#a
import numpy as np
arr = np.array([1,2,3,4,5])
reversed_arr = arr[::-1]
print("Reversed Array = ",reversed_arr)

Reversed Array =  [5 4 3 2 1]


In [13]:
#b
#for x array
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_frequent_x = np.bincount(x).argmax()
indices_x = np.where(x==most_frequent_x)[0]

#for y array
y = np.array([1,1,1,2,3,4,2,4,3,3])
most_frequent_y = np.bincount(y).argmax()
indices_y = np.where(y==most_frequent_y)[0]

print("Most frequent value in x = ",most_frequent_x,"at indices = ",indices_x)
print("Most frequent value in y = ",most_frequent_y,"at indices = ",indices_y)

Most frequent value in x =  1 at indices =  [0 5 7 8 9]
Most frequent value in y =  1 at indices =  [0 1 2]


***Question 3***
For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [15]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

#a
element1 = arr[0,1]

#b
element2 = arr[2,0]

print("Element at (1st row and 2nd column) = ",element1)
print("Element at (3rd row and 1st column) = ",element2)

Element at (1st row and 2nd column) =  20
Element at (3rd row and 1st column) =  70


***Question 4***
Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [17]:
import numpy as np

# Creating 1D array with evenly spaced 25 numbers from 10 to 100
shivam_kumar = np.linspace(10, 100, 25)

# Printing properties
print("Array:", shivam_kumar)
print("Dimensions:", shivam_kumar.ndim)
print("Shape:", shivam_kumar.shape)
print("Total elements:", shivam_kumar.size)
print("Data type:", shivam_kumar.dtype)
print("Total bytes consumed:", shivam_kumar.nbytes)

# Finding transpose using reshape()
transposed_shivam_kumar = shivam_kumar.reshape(25, 1)

# Checking if we can use T attribute
transposed_T = shivam_kumar.T

print("Transpose using reshape():\n", transposed_shivam_kumar)
print("Transpose using T attribute:\n", transposed_T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200
Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


***Question 5***
Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [19]:
import numpy as np

# Creating a 2D array
ucs420_shivam = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

# Computing statistics
mean_val = np.mean(ucs420_shivam)
median_val = np.median(ucs420_shivam)
max_val = np.max(ucs420_shivam)
min_val = np.min(ucs420_shivam)
unique_elements = np.unique(ucs420_shivam)

print("Mean:", mean_val)
print("Median:", median_val)
print("Max Value:", max_val)
print("Min Value:", min_val)
print("Unique Elements:", unique_elements)

# Reshaping to 4x3
reshaped_ucs420_shivam = ucs420_shivam.reshape(4, 3)
print("Reshaped Array (4x3):\n", reshaped_ucs420_shivam)

# Resizing to 2x3
resized_ucs420_shivam = np.resize(ucs420_shivam, (2, 3))
print("Resized Array (2x3):\n", resized_ucs420_shivam)

Mean: 43.333333333333336
Median: 37.5
Max Value: 90
Min Value: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
